# Generated by Django 3.1.3 on 2020-12-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20201206_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='click above Post to read the post ', max_length=255),
        ),
    ]
